---
title: "Ferritin model"
author: "Mikko Arvas"
date: "20.12.2023"
output:
  html_document:
    df_print: paged
---


# Summary


```{r setup, , message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(here)
library(broom)
library(gglm)
library(gtable)
library(grid)

```




# Data loading and preparation 

Load data

```{r}

is.fin <- TRUE


if(is.fin) {
  file<- here("data/ID_data_regression_cohorts_genpop_combined.rdata")
  load(file)
  all_cohorts <- regression_cohorts
  all_cohorts <- all_cohorts %>% 
  filter(!is.na(CRP)) %>% 
  filter(! CRP >= 30)

}

```




```{r}
# men
## menstruation and childbirth variables removed 
regression_data_men <- all_cohorts %>% 
  filter(Group == "Men") %>% 
  dplyr::select(
    log_ferritin, 
    Cohort,
    blood_vol,
    Age,
    donation_count, 
    log_last_donation,
    Smoking
    ) %>%
  mutate(Age = scale(Age, scale = FALSE)[,1],
         donation_count = scale(donation_count, scale = FALSE)[,1],
         log_last_donation = scale(log_last_donation, scale = FALSE)[,1],
         blood_vol = scale(blood_vol, scale = FALSE)[,1],
         donation_count_2 = donation_count^2) %>% 
  relocate(Smoking, .after=donation_count_2)

# premenopausal women
regression_data_pre <- all_cohorts %>% 
  filter(Group == "Pre_menopause_women") %>% 
  dplyr::select(
    log_ferritin, 
    Cohort,
    blood_vol,
    Age, 
    donation_count, 
    log_last_donation,
    Smoking,
    Menstruation, 
    PreviousChildbirth, 
    HormonalContraception
    ) %>%
  mutate(Age = scale(Age, scale = FALSE)[,1],
        donation_count = scale(donation_count, scale = FALSE)[,1],
         log_last_donation = scale(log_last_donation, scale = FALSE)[,1],
         blood_vol = scale(blood_vol, scale = FALSE)[,1],
         donation_count_2 = donation_count^2) %>% 
 relocate(donation_count_2, .after=log_last_donation)

# postmenopausal women 
## menstruation variable removed 
regression_data_post <- all_cohorts %>% 
  filter(Group == "Post_menopause_women") %>% 
  dplyr::select(
    log_ferritin, 
    Cohort,
    blood_vol,
    Age, 
    donation_count, 
    log_last_donation,
    Smoking,
    Menstruation, 
    PreviousChildbirth, 
    HormonalContraception
    ) %>%
  mutate(Age = scale(Age, scale = FALSE)[,1],
         donation_count = scale(donation_count, scale = FALSE)[,1],
         log_last_donation = scale(log_last_donation, scale = FALSE)[,1],
         blood_vol = scale(blood_vol, scale = FALSE)[,1],
         donation_count_2 = donation_count^2) %>% 
  relocate(donation_count_2, .after=log_last_donation)


```

## Models 

```{r}

fit_models <- function(data) {
  sums <- tibble()
  mods <- list()
  mnames <- vector()
  for (i in 1:(ncol(data) - 1)) { # Assuming 'y' is the first column
    mname  <- paste("M", str_pad(string = i,width = 2,pad = 0),sep="")
    variables <- names(data)[2:(i + 1)] # Selecting variables up to i
    modelformula <- paste("log_ferritin ~", paste(variables, collapse = " + ")) 
    # Fit the linear model
    lm_model <- lm(modelformula, data = data)
    
    # Extract model summary using broom's tidy function
    model_summary <- tidy(lm_model,conf.int = TRUE)
    
    # Add information about the model and coefficients to the results data frame
    sums <- bind_rows(
      sums, 
      mutate(model_summary, 
             Model = mname,
             formula = modelformula
      )
    )
    mods <- c(mods,list(lm_model))
    mnames <- c(mnames,mname)
   
  }
   names(mods) <- mnames
  invisible(list(sums=sums,mods=mods))
}

```


```{r}
results_men <- fit_models(regression_data_men)
results_post <- fit_models(regression_data_post)
results_pre <- fit_models(regression_data_pre)
```


# Plots diagnosis


```{r}

plot_models <- function(model_list,color=NULL){
  #cat(length(model_list),"\n")
  alpha <- 0.2
  qqps <- list()
  frps <- list()
  slps <- list()
  rlps <- list()
  for(i in names(model_list)) {
    qq <- ggplotGrob(ggplot(
      model_list[[i]],
      if (is.null(color)) {
        aes(color= NULL)
      } else {
        aes(color= .data[[color]])
      }
      
    ) + 
      stat_normal_qq(alpha = alpha) + 
    theme(legend.position = "none")
    )
  fr <- ggplotGrob(ggplot(
    model_list[[i]],
     if (is.null(color)) {
        aes(color= NULL)
      } else {
        aes(color= .data[[color]])
      }
  ) + 
    stat_fitted_resid(alpha = alpha) + 
    theme(legend.position = "none")
  )
  sl <- ggplotGrob(ggplot(
    model_list[[i]],
     if (is.null(color)) {
        aes(color= NULL)
      } else {
        aes(color= .data[[color]])
      }
  ) + 
    stat_scale_location(alpha = alpha) + 
    theme(legend.position = "none")
  )
  rl <- ggplotGrob(ggplot(
    model_list[[i]],
     if (is.null(color)) {
        aes(color= NULL)
      } else {
        aes(color= .data[[color]])
      }
  ) + 
    stat_resid_leverage(alpha = alpha) + 
    theme(legend.position = "none")
  )
  qqps <- c(qqps,list(qq))
  frps <- c(frps,list(fr))
  slps <- c(slps,list(sl))
  rlps <- c(rlps,list(rl))
} 

    
  mat <- matrix(c(frps,qqps,slps,rlps),ncol=4)
  #cat(dim(mat),"\n")
  mat <- gtable_matrix("diags",
                       mat,
                       widths = unit(c(2, 2,2,2),"inches"),
                heights=unit(rep(2,length(model_list)),"inches")
  )
  mat
}


```



## Men


```{r , warning=FALSE,message=FALSE}
pmen <- plot_models(results_men$mods)
#pmen
```


```{r  fig.width = 8, fig.height = 14}

grid.newpage()
grid.draw(pmen)
```



```{r , warning=FALSE,message=FALSE}
pmen <- plot_models(results_men$mods,color="Cohort")
#pmen
```


```{r  fig.width = 8, fig.height = 14}

grid.newpage()
grid.draw(pmen)
```

## Post

```{r , warning=FALSE,message=FALSE}
ppost <- plot_models(results_post$mods)
```


```{r  fig.width = 8, fig.height = 20}

grid.newpage()
grid.draw(ppost)
```

```{r , warning=FALSE,message=FALSE}
ppost <- plot_models(results_post$mods,color="Cohort")
```


```{r  fig.width = 8, fig.height = 20}

grid.newpage()
grid.draw(ppost)
```

## Pre

```{r , warning=FALSE,message=FALSE}
ppre <- plot_models(results_pre$mods)
```


```{r  fig.width = 8, fig.height = 20}

grid.newpage()
grid.draw(ppre)
```

```{r , warning=FALSE,message=FALSE}
ppre <- plot_models(results_pre$mods,color="Cohort")
```


```{r  fig.width = 8, fig.height = 20}

grid.newpage()
grid.draw(ppre)
```


```{r , warning=FALSE,message=FALSE}
#ppre <- plot_models(list(M4=results_pre$mods$M4,M5=results_pre$mods$M5),color="donation_count")
#grid.newpage()
#grid.draw(ppre)
# Warning messages:
# 1: The following aesthetics were dropped during statistical transformation: colour
# ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
#ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? 

#this need a a bit of thinking if it is really needed
```




# Plot coefficients


```{r}

regressor_values <- c(
 "Age" = "Age",
     "log_last_donation" = "Days since last blood donation (log transformed)",
   "Smokingyes" ="Smoking",
    "donation_count_2" = "Number of blood donations (quadratic)",
    "MenstruationYes" = "Menstruation",
 "HormonalContraceptionyes" = "Hormonal contraception",
    "PreviousChildbirthyes" = "Childbirth in the past",
    "donation_count" = "Number of blood donations",
  #  "CohortHEALTH00" = "Cohort (Health 2000)",
  #  "CohortFINRISK97" = "Cohort (FinRisk 1997)",
 "CohortTHL" = "General population",
    "blood_vol" = "Blood volume"
)

lower <- -1
upper <- 1


makeplotdata <- function(sumtable,group='Pre-menopausal women') {
  sumtable %>% 
    mutate(Group=group) %>% 
    rename(
      m = estimate,
      ll = conf.low,
      ul = conf.high,
      parameter = term
      ) %>% 
    mutate(
    ll = case_when(
      ll < lower ~ lower,
      TRUE ~ ll
    ),
    ul = case_when(
      ul > upper ~ upper,
      TRUE ~ ul
    )
  ) %>% mutate(is.sig = ll < 0 & ul < 0 | ll > 0 & ul > 0) %>% 
    filter(! parameter == "(Intercept)") %>% 
   mutate(regressor = plyr::revalue(parameter, regressor_values)) %>%
     select(-parameter) 
    
}

plotdata <- bind_rows(
makeplotdata(results_pre$sums,group='Pre-menopausal women'),
makeplotdata(results_post$sums,group='Post-menopausal women'),
makeplotdata(results_men$sums,group='Men'),
)
```
```{r fig.width = 8, fig.height = 10}


# Color definition 
color_mapping <- c(  "General population" = "#0000FF",  "New blood donor" = "#008000",  "Age" = "#FFA500",    "Blood volume" = "#FFA500",    "Number of blood donations" = "#FF0000",    "Number of blood donations (quadratic)" = "#FF0000",  
  "Days since last blood donation (log transformed)" = "#FF0000",    "Smoking" = "#800080",    "Childbirth in the past" = "#800080",   "Menstruation" = "#800080",  "Hormonal contraception" = "#800080")

pos <- position_nudge(y=as.numeric(as.factor(plotdata$Group))/5 -0.1) 

p <- ggplot(plotdata, aes(x = m, y = regressor,color=regressor)) + 
  geom_point(position = pos,
             aes(shape = is.sig), 
             size=2) +
  geom_linerange(aes(xmin = ll, xmax = ul), 
                 position = pos,
                 size = 0.8, 
                 linetype = 1
                 ) +
  #scale_color_manual(values = c(  "#0065BD", "#BA0303", "#C50084" ),
  #                   limits = c("Men",  "Post-menopausal women","Pre-menopausal women" )) +
  #scale_fill_manual(values = c(  "#0065BD", "#BA0303", "#C50084" ),
  #                  limits = c("Men",  "Post-menopausal women","Pre-menopausal women" )) +
  scale_shape_manual(values = c(1,16)) +
  xlim(lower,upper)  +   
  geom_vline(xintercept = 0 , color = "grey", linetype = "dotted",
             size = 1) +
  theme(axis.title = element_text(size = 14),
        strip.text =  element_text(size = 14),
        legend.text = element_text(size = 12),
        strip.background = element_rect(fill = "white"),
        strip.background.x = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 10)
  ) +
  guides(shape = "none") +
  theme_classic() +
  xlab("Coefficient") +
  theme(text = element_text(size = 10)) +
  theme(axis.title.y = element_blank()) +
  facet_grid(Model~ Group,scales = "free_y",space = "free_y") +
  theme(legend.position = "none") +
  scale_color_manual(values = c(color_mapping)) 

p


```

